# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

set --prepend fish_function_path /nix/store/sw9zsaf2ya497jra48chamlfach4vm1y-fishplugin-foreign-env-unstable-2020-02-09/share/fish/vendor_functions.d
fenv source /etc/profiles/per-user/riro/etc/profile.d/hm-session-vars.sh >/dev/null
set -e fish_function_path[1]

fish_vi_key_bindings
set -g direnv_fish_mode eval_on_arrow
set fish_color_normal normal
set fish_color_command blue
set fish_color_quote yellow
set fish_color_redirection cyan --bold
set fish_color_end green
set fish_color_error brred
set fish_color_param cyan
set fish_color_comment red
set fish_color_match --background=brblue
set fish_color_selection white --bold --background=brblack
set fish_color_search_match bryellow --background=brblack
set fish_color_history_current --bold
set fish_color_operator brcyan
set fish_color_escape brcyan
set fish_color_cwd green
set fish_color_cwd_root red
set fish_color_valid_path --underline
set fish_color_autosuggestion white
set fish_color_user brgreen
set fish_color_host normal
set fish_color_cancel --reverse
set fish_pager_color_prefix normal --bold --underline
set fish_pager_color_progress brwhite --background=cyan
set fish_pager_color_completion normal
set fish_pager_color_description B3A06D --italics
set fish_pager_color_selected_background --reverse
update_cwd_osc

function __fish_command_not_found_handler --on-event fish_command_not_found
    /nix/store/a9i450s49245p9cinnkg3pqkl8fhykc7-command-not-found $argv
end

source /nix/store/76hb261s44wy4h9kqfl7kgm1naqq8iz6-fzf-0.40.0/share/fzf/key-bindings.fish && fzf_key_bindings


status --is-login; and begin

    # Login shell initialisation


end

status --is-interactive; and begin

    # Abbreviations


    # Aliases
    alias cd.. 'cd ..'
    alias daos doas
    alias daso doas
    alias g lazygit
    alias kls 'lsd --icon never'
    alias l 'lsd --icon never -lh'
    alias la 'lsd --icon never -la'
    alias lks 'lsd --icon never'
    alias ls 'lsd --icon never'
    alias nd 'cd /etc/nixos'
    alias off poweroff
    alias rekey 'nix run .#rekey'
    alias sl 'lsd --icon never'
    alias swc 'doas nixos-rebuild switch --flake /etc/nixos --verbose'
    alias swcs 'doas nixos-rebuild switch --flake /etc/nixos --verbose --max-jobs 1'
    alias up 'nix flake update --commit-lock-file /etc/nixos && swc'

    # Interactive shell initialisation
    # Need to declare here, since something buggy.
    # For foot `jump between prompt` function
    function mark_prompt_start --on-event fish_prompt
        echo -en "\e]133;A\e\\"
    end

    if test "$TERM" != dumb -a \( -z "$INSIDE_EMACS" -o "$INSIDE_EMACS" = vterm \)
        eval (/etc/profiles/per-user/riro/bin/starship init fish)
    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/riro/.local/share/fish/home-manager_generated_completions" $post
    end

    . /nix/store/b204j11ab6b1qlskbh9ky81qya74nvk9-autojump-22.5.3/share/autojump/autojump.fish

    /nix/store/gmiiyc125cq7x0fvbvvyhr1vzgb3dfqx-direnv-2.32.2/bin/direnv hook fish | source


end
